# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:otbn.bzl", "otbn_binary", "otbn_library")

package(default_visibility = ["//visibility:public"])

otbn_library(
    name = "addmv",
    srcs = [
        "addmv.s",
    ],
)

otbn_library(
    name = "submv",
    srcs = [
        "submv.s",
    ],
)

otbn_library(
    name = "mulmv",
    srcs = [
        "mulmv.s",
    ],
)

otbn_library(
    name = "mulv",
    srcs = [
        "mulv.s",
    ],
)

otbn_library(
    name = "trans8",
    srcs = [
        "trans8.s",
    ],
)

otbn_library(
    name = "andv",
    srcs = [
        "andv.s",
    ],
)