# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "benchmark_params",
    hdrs = ["benchmark_params.h"],
    deps = [
        "//sw/device/silicon_creator/lib/sigverify/sphincsplus:shake_offsets",
    ],
)
