# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:otbn.bzl", "otbn_binary", "otbn_library")

package(default_visibility = ["//visibility:public"])

otbn_library(
    name = "ntt_dilithium_4l",
    srcs = [
        "ntt_dilithium_4l.s",
    ],
)

otbn_library(
    name = "ntt_dilithium",
    srcs = [
        "ntt_dilithium.s",
    ],
)

otbn_library(
    name = "intt_dilithium",
    srcs = [
        "intt_dilithium.s",
    ],
)

otbn_library(
    name = "poly_pointwise_dilithium",
    srcs = [
        "poly_pointwise_dilithium.s",
    ],
)

otbn_library(
    name = "poly_pointwise_acc_dilithium",
    srcs = [
        "poly_pointwise_dilithium.s",
    ],
)

otbn_library(
    name = "poly_add_dilithium",
    srcs = [
        "poly_add_dilithium.s",
    ],
)

otbn_library(
    name = "poly_sub_dilithium",
    srcs = [
        "poly_sub_dilithium.s",
    ],
)

otbn_library(
    name = "poly_reduce32_dilithium",
    srcs = [
        "poly_reduce32_dilithium.s",
    ],
)

otbn_library(
    name = "poly_caddq_dilithium",
    srcs = [
        "poly_caddq_dilithium.s",
    ],
)

otbn_library(
    name = "poly_power2round_dilithium",
    srcs = [
        "poly_power2round_dilithium.s",
    ],
)

otbn_library(
    name = "key_pair_dilithium",
    srcs = [
        "key_pair_dilithium.s",
    ],
)

otbn_library(
    name = "verify_dilithium",
    srcs = [
        "verify_dilithium.s",
    ],
)

otbn_library(
    name = "poly_dilithium",
    srcs = [
        "poly_dilithium.s",
    ],
)

otbn_library(
    name = "rounding_dilithium",
    srcs = [
        "rounding_dilithium.s",
    ],
)

otbn_library(
    name = "sign_dilithium",
    srcs = [
        "sign_dilithium.s",
    ],
)